try:
    # result = 23/0 # Wrong Approach 
    x = 12/2 # it is right Approach it don't enter the except Call
except:
    print('Error Happened')
finally:
    print('it wee be always with it ')
print('done')